[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FBP"
authors = [{name = "Elena Fernandez", email = "efdez@iaa.es"}]
dynamic = ["version", "description"]
